### ISSUE TITLE
[question] compatability

### ISSUE THREAD

**Issue by Tom-Neverwinter** [grillbaer/esp32-geiger-counter#1]
Is this code compatible with the Geiger counter kits?

For instance can this be used with this setup?
https://www.youtube.com/watch?v=K28Az3-gV7E&feature=youtu.be

**Comment by grillbaer** [comment]
I also own that (or a similar?) kit. My kit outputs 3.3 V low pulses of about 300 µs length at the VIN pin (using 5 V power supply):
![image](https://user-images.githubusercontent.com/33845511/72366652-f9ddad80-36fa-11ea-983b-d36f1ba1763e.png)
![image](https://user-images.githubusercontent.com/33845511/72366759-301b2d00-36fb-11ea-9701-458a08f1e1aa.png)

3.3 V output is great, since it might be used directly as input for the ESP32. Please make sure that your kit also outputs not more that 3.3 V or you might blow your GPIO!

My current code counts high pulses on GPIO 18, not low pulses.

However, in WiFi mode (GPIO 4 low), the code simply counts rising edges using interrupts. So it should still work out of the box since each pulse always has a rising and a falling edge.

In low-power mode (GPIO 4 high), it uses light sleep to wait for a pulse input change. This will not work directly with the kit, because it expects a high level after the first wake-up and a low level after the second wake-up. You could change the expected level in `main.cpp` `takeSampleLowPower()`. The pulse length of 300 µs should probably be long enough for the light-sleep wake-up, but I'm not absolutely sure.

The factor `STS6_CPM_PER_USPH` used in `main.cpp` to convert count-per-minute to the estimated micro-sievert-per-hour must be replaced with a lower value for that much more insensitive tube.

**Comment by Tom-Neverwinter** [comment]
Thank you for the information :)
