### ISSUE TITLE
Diode and inductor.

### ISSUE THREAD

**Issue by miguerman** [grillbaer/esp32-geiger-counter#3]
Hello. I am looking for the 200v and 500mw zener diodes of the BZX79C200 model that appears in the diagram, but it is difficult for me to get it, can you recommend another 200v zener model, the 10mH inductor cannot be found either. Thanks

**Comment by grillbaer** [comment]
Hi, you may use any series of zener diodes that add up to a voltage drop of about 400 V, e.g. 4 times 100 V in series. There's no need for a special type. Their max power does not matter, since there will be almost no current through it. So simply take the smallest ones. These z-diodes' task is to cut of the generator when their total voltage drop (=the target voltage) is exceeded, which works by a small current starting to flow through them then.

Both z-diodes and fixed inductors should be available from almost any electronics parts retailer.

My favorite retailer in Germany has e.g. this inductor https://www.reichelt.de/festinduktivitaet-axial-hm50-ferrit-10-mh-bi-hm50-103klf-p245509.html?&trstct=pos_3&nbc=1 and these z diodes https://www.reichelt.de/zenerdiode-200-v-2-w-do-41-zy-200-dio-p219675.html?&trstct=pol_2&nbc=1. 
I don't know in which part of the world you live, so perhaps you better look into the products of a local retailer, maybe rs electronics or digikey are there.
